on: push # trigger event

jobs: # define jobs, jobs are running in parallel
  job1: # random job name
    runs-on: ubuntu-latest # runner
    steps: # define steps, steps are running in sequence
      - run: pwd
      - run: ls
  job2:
    runs-on: windows-latest
    steps:
      - run: node --version
